### PR TITLE
Switch to linking with Spike instead of patching, use upstream riscv-test-env

### PR DESCRIPTION
**Pull request by jerryz123**

### CODE REVIEW

**Comment by ksco** [comment]
Thanks!

**Comment by ksco** [comment]
I'm assuming this is related to https://github.com/riscv-software-src/riscv-tests/pull/400#issuecomment-1668694021, if so, I'd like to ask a few questions:

What's the current plan? Put content from this repo into upstream riscv-tests? Or create a new one?

If upstreaming, there must be a lot of work to do, where should we do this work? Under the current repo until it's qualified to be upstreaming?

**Comment by jerryz123** [comment]
> What's the current plan? Put content from this repo into upstream riscv-tests? Or create a new one?

I think keeping this as a standalone repo is cleaner. However, donating to riscv/, riscv-software-src/, or chipsalliance/ might be good.

**Comment by ksco** [comment]
> However, donating to riscv/, riscv-software-src/, or chipsalliance/ might be good.

I'd love to do that.

**Comment by jerryz123** [comment]
I think riscv-software-src makes the most sense. I'm not sure who manages that organization though.

**Comment by ksco** [comment]
Yeah, but I heard they're considering https://github.com/hushenwei2000/rvv-atg as a candidate. Not sure how that goes, did you hear anything? In any case, I still hope that there will be an official repo that everyone can contribute to.

**Comment by jerryz123** [comment]
I personally prefer this one, but more tests is always good.

**Comment by ksco** [comment]
Thanks, I'll take the time to make it more upstream-friendly. I think the first thing to do is to rewrite the generator in Python, which seems to be the language of choice for doing this kind of thing.

**Comment by ksco** [comment]
Huh, which version of Spike are you using? I got this error when running `make`:

```
g++ -std=c++17 -I/root/playground/riscv/include -L/root/playground/riscv/lib pspike/pspike.cc -lriscv -lfesvr -o build/pspike
pspike/pspike.cc: In function 'int main(int, char**)':
pspike/pspike.cc:99:20: error: no matching function for call to 'sim_t::sim_t(cfg_t*, bool, std::vector<std::pair<long unsigned int, mem_t*> >&, std::vector<const device_factory_t*>&, std::vector<std::__cxx11::basic_string<char> >&, debug_module_config_t&, std::nullptr_t, bool, std::nullptr_t, bool, std::nullptr_t)'
   99 |             nullptr);
      |                    ^
In file included from pspike/pspike.cc:4:
/root/playground/riscv/include/riscv/sim.h:28:3: note: candidate: 'sim_t::sim_t(const cfg_t*, bool, std::vector<std::pair<long unsigned int, abstract_mem_t*> >, std::vector<const device_factory_t*>, const std::vector<std::__cxx11::basic_string<char> >&, const debug_module_config_t&, const char*, bool, const char*, bool, FILE*)'
   28 |   sim_t(const cfg_t *cfg, bool halted,
      |   ^~~~~
/root/playground/riscv/include/riscv/sim.h:29:56: note:   no known conversion for argument 3 from 'vector<pair<[...],mem_t*>>' to 'vector<pair<[...],abstract_mem_t*>>'
   29 |         std::vector<std::pair<reg_t, abstract_mem_t*>> mems,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
make: *** [Makefile:43: build-patcher-spike] Error 1
```

Seems related to this commit submitted 3 weeks ago: https://github.com/riscv-software-src/riscv-isa-sim/commit/cb013516665addb45dadd197028762fd3757bdb0

**Comment by ksco** [comment]
Fixed in https://github.com/ksco/riscv-vector-tests/commit/6a23892a5ab0cc72f4867cc95186b3528c99c2a0, it should be better to stick to the latest Spike.

**Pull request merged**
